data:
  sequence_length: 90
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  batch_size: 768
  num_workers: 8
  prefetch_factor: 4
  pin_memory: true
  persistent_workers: true
  parquet_file: outputs/part1_pinszc/zero_curtain_enhanced_cryogrid_physics_dataset.parquet
  pinszc_ground_truth: outputs/part1_pinszc/zero_curtain_enhanced_cryogrid_physics_dataset.parquet
  temporal_coverage: seasonal
model:
  d_model: 256
  n_heads: 8
  n_layers: 4
  dropout: 0.2
  liquid_units: 128
  liquid_layers: 2
  pattern_analysis:
    enabled: true
  liquid_hidden: 128
training:
  epochs: 10
  learning_rate: 0.0001
  weight_decay: 0.0001
  early_stopping_patience: 3
  gradient_clip: 0.5
  use_amp: true
  amp_dtype: float16
  accumulation_steps: 1
  compile_model: true
  channels_last: true
  tf32: true
  validate_every: 2
teacher_forcing:
  initial_ratio: 0.5
  final_ratio: 0.1
  curriculum_schedule: exponential
  decay_rate: 0.3
output:
  models_dir: outputs/part2_geocryoai/models
  logs_dir: logs
  cache_dir: outputs/part2_geocryoai/cache
